---
title: "05_piRNAcluster_plot.Rmd"
author: "Xinyu Xiang"
date: "2025-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggridges)
library(ggpubr)
library(tidyr)
library(dplyr)
library(stringr)
library(ggrastr)
library(DESeq2)
library(pheatmap)
library(circlize) 

```

```{r configure}
### setup ###
metadata <- read.table("./metadata_merge.txt", stringsAsFactors = FALSE, header=TRUE)
metadata

dir_order<- c("bi:plus-minus", "bi:minus-plus", "mono:plus", "mono:minus")
dir_col <- c("bi:plus-minus" = "#45502A", "bi:minus-plus" = "#BDC2B3", "mono:plus" = "#835534", "mono:minus" = "#D3C3B8")
type_col <- c("orig" = "#9e2a2b", "shuf" = "#293241")

## parameter for circos plot
cutoff = 0
ymax = 17
condition_col <- c("testis-1" = "#354f52", "testis-2" = "#354f52", "oocyte-1" = "#9f86c0", "oocyte-2" = "#9f86c0")
fwd_col = c("testis-1" = "#286566", "testis-2" = "#286566", "oocyte-1" = "#5c2862", "oocyte-2" = "#5c2862") 
rev_col = c("testis-1" = "#3f9497", "testis-2" = "#3f9497", "oocyte-1" = "#873388", "oocyte-2" = "#873388")
condition_merge_col <- c("testis" = "#354f52", "oocyte" = "#9f86c0")
fwd_merge_col = c("testis" = "#286566", "oocyte" = "#5c2862") 
rev_merge_col = c("testis" = "#3f9497", "oocyte" = "#873388")

## input cytoband file
cytoband.df = read.table("../reference_AmexG_v6.0/AmexG_v6.0-DD.cytoBand.txt",sep = "\t", colClasses = c("character", "numeric",  "numeric", "character", "character"))
head(cytoband.df)

```



# 01. barplot of piRNA cluster directionality
```{r}
##### clean data #####
data.ls <- list()
type.ls <- list()
for (Sample in metadata$sample) {
data.ls[[Sample]] <- read.delim(paste0("./14_piRNAcluster_v2/00_cluster_bed/", Sample, ".cluster_anno.bed"), sep="\t", stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "Cluster", "MappedSequenceReads", "Strand", "Directionality"))

type.ls[[Sample]] <- data.ls[[Sample]] %>% group_by(Directionality) %>% summarise(ClusterNum = n()) %>% mutate(ClusterFreq = ClusterNum/sum(ClusterNum), sample = Sample)

}
type.df <- do.call(rbind, type.ls)
write.csv(type.df, paste0("./14_piRNAcluster_v2/02_barplot_directionality_freq/barplot_directionality_freq.csv"), quote = FALSE, row.names = FALSE)


##### plot barplot #####
type.df <- type.df %>% mutate(sample = factor(sample, levels = metadata$sample), 
                              Directionality = factor(Directionality, levels = dir_order))

pdf(paste0("./14_piRNAcluster_v2/02_barplot_directionality_freq/barplot_directionality_freq.pdf"), height = 4, width = 5)
p1 <- ggplot(data=type.df, aes(x=sample, y=ClusterNum, fill=Directionality)) + 
  geom_bar(colour = "black", stat = "identity", width = 0.8) + 
  theme_classic(base_size = 12) + scale_fill_manual(values = dir_col) +
  theme(axis.text.x = element_text(angle = 90)) 
  #scale_y_continuous(limits = c(0, 250))
plot(p1)
dev.off()

```



# 02. ridgeplot of piRNA cluster length distribution
```{r}
data.ls <- list()
length.ls <- list()

##### clean data #####
for (Sample in metadata$sample) {
data.ls[[Sample]] <- read.delim(paste0("./14_piRNAcluster_v2/00_cluster_bed/", Sample, ".cluster_anno.bed"), sep="\t", stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "Cluster", "MappedSequenceReads", "Strand", "Directionality"))
length.ls[[Sample]] <- data.ls[[Sample]] %>% mutate(Length.kb = round( (End - Start)/1000, 3), 
                                                    sample = Sample, condition = sub("..$", "", Sample))
}
length.df <- do.call(rbind, length.ls)
write.csv(length.df, paste0("./14_piRNAcluster_v2/03_ridgeplot_directionality_length/ridgeplot_directionality_length.csv"), quote = FALSE, row.names = FALSE)




##### plot ridgeplot #####
length.df <- length.df %>% mutate(sample = factor(sample, levels = metadata$sample), 
                                  Directionality = factor(Directionality, levels = rev(dir_order)),
                                  condition = factor(condition, levels = c("testis", "oocyte")))

pdf(paste0("./14_piRNAcluster_v2/03_ridgeplot_directionality_length/ridgeplot_directionality_length.pdf"), height = 4, width = 7)
p1 <- ggplot(length.df, aes(x = Length.kb, y = Directionality, fill = Directionality)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, 100/5)) +
  scale_fill_manual(values = dir_col) +
  facet_grid( ~ condition)
plot(p1)
dev.off()



```



# 03. circos barplot of piRNA cluster + coverage
## 3.1 plot circos barplot, piRNA cluster + coverage, selected chr
```{r circos barplot}
##### input piRNA cluster and coverage #####
binsize="1000000"
cluster.ls = list()
cluster.merge.ls = list()
coverage.ls = list()
coverage.merge.ls = list()

for (Sample in metadata$sample) {
# cluster
cluster.ls[[Sample]] <- read.delim(paste0("./14_piRNAcluster_v2/00_cluster_bed/", Sample, ".cluster_anno.bed"), sep="\t", stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "Cluster", "MappedSequenceReads", "Strand", "Directionality"))
# coverage (log2(RPM+1))
coverage.ls[[Sample]][[1]] = read.table(paste0("./14_piRNAcluster_v2/06_circos/", Sample, "_genome_srt_edit.pirna.fwd.bin", binsize, ".log2RPM.bed"), stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "log2RPMplus1"))
coverage.ls[[Sample]][[2]] = read.table(paste0("./14_piRNAcluster_v2/06_circos/", Sample, "_genome_srt_edit.pirna.rev.bin", binsize, ".log2RPM.bed"), stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "log2RPMplus1"))
}

# merge clusters and calculate log2RPMplus1mean
cluster.merge.ls[["testis"]] <- rbind(cluster.ls[["testis-1"]], cluster.ls[["testis-2"]])
cluster.merge.ls[["oocyte"]] <- rbind(cluster.ls[["oocyte-1"]], cluster.ls[["oocyte-2"]])
coverage.merge.ls[["testis"]][[1]] <- rbind(coverage.ls[["testis-1"]][[1]], coverage.ls[["testis-2"]][[1]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage.merge.ls[["testis"]][[2]] <- rbind(coverage.ls[["testis-1"]][[2]], coverage.ls[["testis-2"]][[2]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage.merge.ls[["oocyte"]][[1]] <- rbind(coverage.ls[["oocyte-1"]][[1]], coverage.ls[["oocyte-2"]][[1]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage.merge.ls[["oocyte"]][[2]] <- rbind(coverage.ls[["oocyte-1"]][[2]], coverage.ls[["oocyte-2"]][[2]]) %>% 
 group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()

##### sep rep plot #####
pdf(paste0("./14_piRNAcluster_v2/06_circos_plot/20240705circos_piRNAcluster.seprep.zoomin.pdf"), height = 10, width = 10)
### set up circus plot ###
circos.par("start.degree" = 90, "gap.degree" = c(8,8), cell.padding = c(0, 0, 0, 0), track.margin = c(0, 0))
circos.initializeWithIdeogram(cytoband.df, chromosome.index = c("chr3p", "chr13p"), 
                              plotType = c("axis", "labels")) 
# text(0, 0, paste0("axolotl piRNA cluster"), cex = 2, font = 2)

### plot tracks ###
for (Sample in metadata$sample) {
# line plot of coverage 
circos.genomicTrackPlotRegion(coverage.ls[[Sample]], ylim = c(-ymax, ymax), track.height = uh(12, "mm"), 
                              panel.fun = function(region, value, ...) {
    j = getI(...)
    if(j == 1) {
        circos.genomicLines(region, value, area = TRUE, baseline = 0, col = fwd_col[Sample], border = NA)
    } else {
        circos.genomicLines(region, -value, area = TRUE, baseline = 0, col = rev_col[Sample], border = NA)
    }
}, bg.border = NA)

# box plot of piRNA cluster 
circos.genomicTrackPlotRegion(cluster.ls[[Sample]], track.height = uh(1.5, "mm"),  #ylim = c(0, ymax),
    panel.fun = function(region, value, ...) {
        circos.genomicRect(region, value, border = condition_col[Sample])
}, bg.border = NA)

}
circos.clear()
dev.off()

##### merge rep plot #####
pdf(paste0("./14_piRNAcluster_v2/06_circos_plot/20240705circos_piRNAcluster.mergerep.zoomin.pdf"), height = 10, width = 10)
### set up circus plot ###
circos.par("start.degree" = 90, "gap.degree" = c(8,8), cell.padding = c(0, 0, 0, 0), track.margin = c(0, 0))
circos.initializeWithIdeogram(cytoband.df, chromosome.index = c("chr3p", "chr13p"), 
                              plotType = c("axis", "labels")) 
# text(0, 0, paste0("axolotl piRNA cluster"), cex = 2, font = 2)

### plot tracks ###
for (Cond in c("testis", "oocyte")) {
# line plot of coverage 
circos.genomicTrackPlotRegion(coverage.merge.ls[[Cond]], ylim = c(-ymax, ymax), track.height = uh(12, "mm"), 
                              panel.fun = function(region, value, ...) {
    j = getI(...)
    if(j == 1) {
        circos.genomicLines(region, value, area = TRUE, baseline = 0, col = fwd_merge_col[Cond], border = NA)
    } else {
        circos.genomicLines(region, -value, area = TRUE, baseline = 0, col = rev_merge_col[Cond], border = NA)
    }
}, bg.border = NA)

# box plot of piRNA cluster 
circos.genomicTrackPlotRegion(cluster.merge.ls[[Cond]], track.height = uh(1.5, "mm"),  #ylim = c(0, ymax),
    panel.fun = function(region, value, ...) {
        circos.genomicRect(region, value, border = condition_merge_col[Cond])
}, bg.border = NA)

}
circos.clear()
dev.off()

```



## 3.2 plot circos barplot, piRNA cluster + coverage, all chr
```{r circos barplot}
binsize="10000000"
cytoband2.df = cytoband.df %>% mutate(V3 = ceiling(V3/10)) # scale plot length
cluster2.ls = list()
cluster2.merge.ls = list()
coverage2.ls = list()
coverage2.merge.ls = list()

for (Sample in metadata$sample) {
# cluster
cluster2.ls[[Sample]] <- read.delim(paste0("./14_piRNAcluster_v2/00_cluster_bed/", Sample, ".cluster_anno.bed"), sep="\t", stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "Cluster", "MappedSequenceReads", "Strand", "Directionality")) %>% mutate(Start = ceiling(Start/10), End = ceiling(End/10))

# coverage (log2(RPM+1))
# coverage (log2(RPM+1))
coverage2.ls[[Sample]][[1]] = read.table(paste0("./14_piRNAcluster_v2/06_circos/", Sample, "_genome_srt_edit.pirna.fwd.bin", binsize, ".log2RPM.bed"), stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "log2RPMplus1")) %>% mutate(Start = ceiling(Start/10), End = ceiling(End/10))
coverage2.ls[[Sample]][[2]] = read.table(paste0("./14_piRNAcluster_v2/06_circos/", Sample, "_genome_srt_edit.pirna.rev.bin", binsize, ".log2RPM.bed"), stringsAsFactors = FALSE, header = FALSE, col.names = c("Chr", "Start", "End", "log2RPMplus1")) %>% mutate(Start = ceiling(Start/10), End = ceiling(End/10))
}


# merge clusters and calculate log2RPMplus1mean
cluster2.merge.ls[["testis"]] <- rbind(cluster2.ls[["testis-1"]], cluster2.ls[["testis-2"]])
cluster2.merge.ls[["oocyte"]] <- rbind(cluster2.ls[["oocyte-1"]], cluster2.ls[["oocyte-2"]])
coverage2.merge.ls[["testis"]][[1]] <- rbind(coverage2.ls[["testis-1"]][[1]], coverage2.ls[["testis-2"]][[1]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage2.merge.ls[["testis"]][[2]] <- rbind(coverage2.ls[["testis-1"]][[2]], coverage2.ls[["testis-2"]][[2]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage2.merge.ls[["oocyte"]][[1]] <- rbind(coverage2.ls[["oocyte-1"]][[1]], coverage2.ls[["oocyte-2"]][[1]]) %>% 
  group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()
coverage2.merge.ls[["oocyte"]][[2]] <- rbind(coverage2.ls[["oocyte-1"]][[2]], coverage2.ls[["oocyte-2"]][[2]]) %>% 
 group_by(Chr, Start, End) %>% summarize(log2RPMplus1mean = mean(log2RPMplus1)) %>% ungroup()


##### sep rep plot #####
pdf(paste0("./14_piRNAcluster_v2/06_circos_plot/20240705circos_piRNAcluster.seprep.allchr.pdf"), height = 7, width = 7)
circos.par(gap.degree = c(rep(1, 28-1),3), start.degree = 90, cell.padding = c(0, 0, 0, 0), track.margin = c(0, 0))

circos.initializeWithIdeogram(cytoband2.df, chromosome.index = cytoband2.df$V1, 
                              plotType = c("labels"))
# text(0, 0, paste0("axolotl piRNA cluster"), cex = 2, font = 2)

### plot tracks ###
for (Sample in metadata$sample) {
# line plot of coverage 
circos.genomicTrackPlotRegion(coverage2.ls[[Sample]], ylim = c(-ymax, ymax), track.height = uh(12, "mm"), 
                              panel.fun = function(region, value, ...) {
    j = getI(...)
    if(j == 1) {
        circos.genomicLines(region, value, area = TRUE, baseline = 0, col = fwd_col[Sample], border = NA)
    } else {
        circos.genomicLines(region, -value, area = TRUE, baseline = 0, col = rev_col[Sample], border = NA)
    }
}, bg.border = NA)

# box plot of piRNA cluster 
circos.genomicTrackPlotRegion(cluster2.ls[[Sample]], track.height = uh(1.5, "mm"), 
    panel.fun = function(region, value, ...) {
        circos.genomicRect(region, value, border = condition_col[Sample])
}, bg.border = NA)

}
circos.clear()
dev.off()


##### merge rep plot #####
pdf(paste0("./14_piRNAcluster_v2/06_circos_plot/20240705circos_piRNAcluster.mergerep.allchr.pdf"), height = 10, width = 10)
### set up circus plot ###
circos.par(gap.degree = c(rep(1, 28-1),3), start.degree = 90, cell.padding = c(0, 0, 0, 0), track.margin = c(0, 0))

circos.initializeWithIdeogram(cytoband2.df, chromosome.index = cytoband2.df$V1, 
                              plotType = c("labels"))
# text(0, 0, paste0("axolotl piRNA cluster"), cex = 2, font = 2)

### plot tracks ###
for (Cond in c("testis", "oocyte")) {
# line plot of coverage 
circos.genomicTrackPlotRegion(coverage2.merge.ls[[Cond]], ylim = c(-ymax, ymax), track.height = uh(12, "mm"), 
                              panel.fun = function(region, value, ...) {
    j = getI(...)
    if(j == 1) {
        circos.genomicLines(region, value, area = TRUE, baseline = 0, col = fwd_merge_col[Cond], border = NA)
    } else {
        circos.genomicLines(region, -value, area = TRUE, baseline = 0, col = rev_merge_col[Cond], border = NA)
    }
}, bg.border = NA)

# box plot of piRNA cluster 
circos.genomicTrackPlotRegion(cluster2.merge.ls[[Cond]], track.height = uh(1.5, "mm"),  #ylim = c(0, ymax),
    panel.fun = function(region, value, ...) {
        circos.genomicRect(region, value, border = condition_merge_col[Cond])
}, bg.border = NA)

}
circos.clear()
dev.off()


```


# 04. piRNA cluster cumulative fraction
```{r}
input.ls <- list()
data.ls <- list()
### clean results.table ###
for (Sample in metadata$sample) {

input.ls[[Sample]] <- read.delim(paste0("./14_piRNAcluster_v2/08_proTRAC_cluster_stat/", Sample, ".results.table.txt"), header = F)
data.ls[[Sample]] <- data.frame(
  Cluster = sub(".* ", "", input.ls[[Sample]]$V1),
  Chr = sub(".*: ", "", input.ls[[Sample]]$V2),
  Coordinates = sub(".*: ", "", input.ls[[Sample]]$V3),
  Size_bp = as.numeric(sub(".*: ", "", input.ls[[Sample]]$V4)),
  Hits_absolute = as.numeric(sub(".*: ", "", input.ls[[Sample]]$V5)),
  Hits_RPM = as.numeric(sub(".*: ", "", input.ls[[Sample]]$V6)),
  Hits_RPKM = as.numeric(sub(".*: ", "", input.ls[[Sample]]$V7)),
  Hits_1T_percent = as.numeric(sub("%", "", sub(".*: ", "", input.ls[[Sample]]$V8))),
  Hits_10A_percent = as.numeric(sub("%", "", sub(".*: ", "", input.ls[[Sample]]$V9))),
  Hits_23_33_percent = as.numeric(sub("%", "", sub(".*: ", "", input.ls[[Sample]]$V10))),
  Main_strand_percent = as.numeric(sub("%", "", sub(".*: ", "", input.ls[[Sample]]$V11))),
  Directionality = sub(".*: ", "", input.ls[[Sample]]$V12)
) %>%
  separate(Coordinates, into = c("Start", "End"), sep = "-", convert = TRUE)


write_delim(data.ls[[Sample]], paste0("./14_piRNAcluster_v2/08_proTRAC_cluster_stat/", Sample, ".results.table.clean.txt"), delim = "\t", col_names = T, quote_escape = "none")

}

```


```{r}
### rank and calculate cumulative fraction
plot.ls <- list()
for (Sample in metadata$sample) {

## calculate cumulative fraction by Hits_RPM
plot.ls[[Sample]] <- data.ls[[Sample]] %>%
  arrange(desc(Hits_RPM)) %>%  
  mutate(Rank = row_number(), 
         CumFracRPM = cumsum(Hits_RPM) / sum(Hits_RPM),
         sample = Sample)

## calculate percentile_90
  percentile_90_rank <- min(plot.ls[[Sample]]$Rank[plot.ls[[Sample]]$CumFracRPM >= 0.90])

pdf(paste0("./14_piRNAcluster_v2/08_proTRAC_cluster_stat/dotplot_cumulative_fraction.", Sample, ".pdf"), height = 4, width = 4)
p <- ggplot(plot.ls[[Sample]], aes(x = Rank)) +
  # left y-axis: CumFracRPM
  geom_point(aes(y = CumFracRPM), color = "orange", size = 0.5) +  
  # right y-axis: Hits_RPKM
  geom_point(aes(y = Hits_RPKM / max(Hits_RPKM)), # proportional right y-axis to left
            color = "grey", linetype = "dashed", size = 0.5) +
  scale_y_continuous(
    sec.axis = sec_axis(~ . * max(plot.ls[[Sample]]$Hits_RPKM), name = "Hits_RPKM")) + # original right y-axis scale
  
  # add percentile_90
  geom_vline(xintercept = percentile_90_rank, linetype = "dashed", color = "red") +
  annotate("text", x = percentile_90_rank, y = 0, 
         label = paste0("90th: ", percentile_90_rank), color = "red", size = 3) + 

  labs(title = Sample,
       x = paste0("Ranked clusters (by Hits_RPM)")) +
  theme_bw() +
  theme(
    axis.title.y.left = element_text(color = "orange"),
    axis.title.y.right = element_text(color = "grey"),
    legend.position = "none",
    panel.grid = element_blank()
  )

plot(p)
dev.off()

}

output.df <- do.call(rbind, plot.ls)
write.csv(output.df, paste0("./14_piRNAcluster_v2/08_proTRAC_cluster_stat/dotplot_cumulative_fraction.csv"), quote = F, row.names = F)

```

